import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import UserHeader from "@/components/Dashboard/UserHeader";
import { SideBar } from "@/components/Dashboard/SideBar";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode,
}>) {
  return (
    <html lang="en">
      <body>
        <main className="w-screen h-screen bg-white grid md:grid-cols-5 grid-cols-1">
          <SideBar />
          <div className="col-span-1 md:col-span-4 p-8 max-h-screen overflow-y-auto">
            <UserHeader />
            {children}
          </div>
        </main>
        <Toaster />
      </body>
    </html>
  );
}
